name: ci-cd-workflow
on: workflow_dispatch

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: download source code
        uses: actions/checkout@v4
      - name: donwload databricks cli
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      - name: create dbx config file
        run:  |
              cat <<EOF > ~/.databrickscfg
              [DEFAULT]
              host  = https://dbc-137322c2-693c.cloud.databricks.com/
              token = ${{secrets.DBX_TOKEN}}
              EOF
      - name: list files
        run:  ls
      - name: dev deployment
        run: databricks bundle deploy --target dev
      - name: run test cases
        run: python workflow.py ${{secrets.DBX_TOKEN}}
       
