name: ci-cd-workflow
on: workflow_dispatch

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: download source code
        uses: actions/checkout@v4
      - name: donwload databricks cli
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      - name: check dbx cli version
        run:  databricks --version
      - name: create dbx config file
        run:  cat <<EOF > .databrickscfg
              [DEFAULT]
              host  = https://dbc-137322c2-693c.cloud.databricks.com/
              token = dapib06dfed29cd4687f07b7f5833a4191d8
              EOF
      - name: list files
        run: ls
       
