name: ci-cd-workflow
on: workflow_dispatch


jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: download source code
        uses: actions/checkout@v4
      - name: donwload databricks cli
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      - name: create dbx config file
        run:  |
              cat <<EOF > ~/.databrickscfg
              [DEFAULT]
              host  = https://dbc-137322c2-693c.cloud.databricks.com/
              token = ${{secrets.DBX_TOKEN}}
              EOF
      - name: list files
        run:  ls
      - name: dev deployment
        run: databricks bundle deploy --target dev
      - name: run test cases
        id: run-tests
        run: |
              output=$(python workflow.py ${{ secrets.DBX_TOKEN }})

              echo "test_output<<EOF" >> $GITHUB_OUTPUT
              echo "$output" >> $GITHUB_OUTPUT
              echo "EOF" >> $GITHUB_OUTPUT
              echo "output = $output"
              

      - name: print test results
        run: |
             cat <<EOF
                    ${{ steps.run-tests.outputs.test_output }}
             EOF
      - name: check failed test cases
        run : |
              python << EOF
              import ast
              dict_output = ast.literal_eval(${{ steps.run-tests.outputs.test_output }}['test_case_result'])
              failed_test_cases = [x for x in dict_output if x['test case result'] == 'failed']
              print(failed_test_cases)
                      #  if failed_test_cases:
                      #     for test_case in failed_test_cases:
                      #       print(f"Below test case failed: {test_case['test case desc']}")
                      #       print(1/0)
                      
                    
              EOF
             


       
