name: ci-cd-workflow
on: workflow_dispatch

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: download source code
        uses: actions/checkout@v4
      - name: donwload databricks cli
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      - name: check dbx cli version
        run:  databricks --version
